version: 2.1
orbs:
  clair: ovotech/clair-scanner@1.4.25
 
jobs:
  container_vulnerability_scan:
    executor: clair/default
    steps:
      - checkout 
      - clair/scan:
          image: entur/cci-toolbox:1.1
 
workflows:
  vulnerability_scan:
    jobs:
      - container_vulnerability_scan:
         context: global